name: yolov5
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19.5
  - opencv=4.5.5
  - pillow=8.4.0
  - tqdm=4.62.3
  - pytorch=1.9.1
  - torchvision=0.10.1
  - pip
  - pip:
    - yolov5==5.0.5
    - psycopg2-binary==2.9.1
    - moviepy==1.0.3
    - SpeechRecognition==3.8.1
    - twilio==6.63.0
